DROP DATABASE IF EXISTS user_db;
CREATE DATABASE user_db;

USE DATABASE user_db;

CREATE TABLE services(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     type VARCHAR(50), price VARCHAR(50));
CREATE TABLE employees(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(50),title VARCHAR(25),
    wages VARCHAR(25), hired VARCHAR(25));
